Repository Melffys/WeKitBucket, pull requests merged in 2024-07, with the labels that each got.

#17 ✨feat: 헤더 컴포넌트 제작
  next.config.mjs
  package.json
  src/_components/RedirectButton.tsx
  src/apis/auth/postSignout.ts
  src/apis/user/getUsersMe.ts
  src/app/(auth)/login/_components/Button.tsx
  src/app/(auth)/login/_components/ErrorText.tsx
  src/app/(auth)/login/_components/Form.tsx
  src/app/(auth)/login/_components/Input.tsx
  src/app/(auth)/login/_components/Label.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_components/Button.tsx
  src/app/(auth)/signup/_components/ErrorText.tsx
  src/app/(auth)/signup/_components/Input.tsx
  src/app/(auth)/signup/_components/Label.tsx
  src/app/(auth)/signup/_components/SignUpForm.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/wiki/[code]/page.tsx
  src/app/(boards)/boards/components/bestArticles/BestSwiper.tsx
  src/app/_components/Header.tsx
  src/app/_components/_Header/AlarmModal.tsx
  src/app/_components/_Header/AlarmModalHeader.tsx
  src/app/_components/_Header/HeaderLeft.tsx
  src/app/_components/_Header/HeaderRight.tsx
  src/app/_components/_Header/MenuModalHeader.tsx
  src/app/_components/_Header/MessageAlarm.tsx
  src/app/_components/_Header/ModalComponent.tsx
  src/app/_components/_Header/NoAlarmMessage.tsx
  src/app/_components/_Header/NotUserDropDown.tsx
  src/app/_components/_Header/UserDropDown.tsx
  src/app/_components/_Header/UserProfileDropdown.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/icons/alarmIcon.svg
  src/assets/icons/hamburgerMenu.svg
  src/assets/icons/userProfileIcon.svg
  src/assets/icons/wikidLogo.svg
  src/assets/images/rabbit.webp
  src/context/AuthContext.tsx
  src/types/user.ts
  src/utils/debounce.ts
  tailwind.config.js
  yarn.lock
Labels: ✨ Feat

#23 ✨ Feat/login: 아이디, 비밀번호 유효성 체크 및 메인페이지로 이동
  src/app/(auth)/login/_components/Form.tsx
  src/app/(auth)/login/page.tsx
  src/app/(boards)/boards/components/bestArticles/BestPostCard.tsx
  src/app/not-found.tsx
  yarn.lock
Labels: ✨ Feat

#24 ✨ feat/wikilist: wikilist페이지 구현, usequery라이브러리 설치 및 관련 유틸 함수 구현, api 자잘하게 수정
  .env
  .eslintrc.json
  next.config.mjs
  package.json
  src/apis/article/getArticles.ts
  src/apis/article/postArticles.ts
  src/apis/article/test.ts
  src/apis/notification/deleteNotifications.ts
  src/apis/notification/getNotifications.ts
  src/apis/profile/getProfiles.ts
  src/app/(auth)/wiki/[code]/page.tsx
  src/app/(boards)/boards/components/allArticles/AllArticleSection.tsx
  src/app/(boards)/boards/page.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/app/wiki/[code]/page.tsx
  src/app/wikilist/_components/Input.tsx
  src/app/wikilist/_components/InputResult.tsx
  src/app/wikilist/_components/PageItem.tsx
  src/app/wikilist/_components/Pagination.tsx
  src/app/wikilist/_components/Profile.tsx
  src/app/wikilist/_components/ProfileList.tsx
  src/app/wikilist/page.tsx
  src/assets/icons/leftArrow.svg
  src/assets/icons/link.svg
  src/assets/icons/noProfilePicture.svg
  src/assets/icons/rightArrow.svg
  src/hooks/useResponsive.tsx
  src/styles/globals.css
  src/types/profiles.d.ts
  yarn.lock
Labels: ✨ Feat

#27 ✨feat(modal): 공통 모달 컴포넌트 작업
  package.json
  src/_components/CommonModal.tsx
  src/_components/Modal.tsx
  src/_components/Portal.tsx
  src/assets/icons/close.svg
  tailwind.config.js
  yarn.lock
Labels: ✨ Feat

#25 ✨ feat/apis: interceptor추가
  src/apis/article/getArticles.ts
  src/apis/auth/postRefreshToken.ts
  src/apis/notification/deleteNotifications.ts
  src/apis/notification/getNotifications.ts
  src/apis/profile/getProfiles.ts
  src/app/page.tsx
  src/app/test/page.tsx
  src/utils/fetchInstance.ts
Labels: ✨ Feat

#30 🐛 Fix: 사용자 정보 동기화 이슈 문제 해결
  src/_components/RedirectButton.tsx
  src/apis/article/getArticles.ts
  src/apis/profile/getProfiles.ts
  src/app/_components/_Header/HeaderRight.tsx
  src/app/_components/_Header/UserProfileDropdown.tsx
  src/app/not-found-code/page.tsx
  src/context/AuthContext.tsx
Labels: 🐛 Fix

#31 ✨Feat/details: 게시글 상세 페이지 추가
  src/apis/article/deleteArticlesLike.ts
  src/apis/article/getArticles.ts
  src/apis/article/getArticlesId.ts
  src/apis/article/postArticlesLike.ts
  src/apis/comment/getComment.ts
  src/app/(boards)/boards/[id]/components/CommentForm.tsx
  src/app/(boards)/boards/[id]/components/CommentList.tsx
  src/app/(boards)/boards/[id]/components/DeleteModal.tsx
  src/app/(boards)/boards/[id]/components/DetailSection.tsx
  src/app/(boards)/boards/[id]/page.tsx
  src/app/(boards)/boards/components/allArticles/AllArticleSection.tsx
  src/app/(boards)/boards/components/bestArticles/BestPostCard.tsx
  src/app/(boards)/boards/components/bestArticles/BestPostList.tsx
  src/assets/icons/defaultProfile.svg
  src/assets/icons/like.svg
  src/assets/icons/pencilIcon.svg
  src/assets/icons/trashIcon.svg
  src/types/articles.d.ts
  src/utils/fetchInstance.ts
Labels: ✨ Feat

#26 ✨ Feat: 토스트 기능 및 컨텍스트 제작
  src/_components/Toast.tsx
  src/_components/ToastPopup.tsx
  src/apis/profile/getProfiles.ts
  src/app/(auth)/login/_components/Form.tsx
  src/app/(auth)/signup/_components/Button.tsx
  src/app/_components/_Header/HeaderRight.tsx
  src/app/_components/_Header/NoAlarmMessage.tsx
  src/app/layout.tsx
  src/assets/icons/snackbar_alert.svg
  src/assets/icons/snackbar_check.svg
  src/assets/icons/snackbar_info.svg
  src/context/ToastContext.tsx
Labels: ✨ Feat

#34 ✨ feat(image error): 이미지 에러 체크 커스텀 훅
  src/app/(boards)/boards/[id]/components/CommentList.tsx
  src/hooks/useImageLoad.ts
Labels: ✨ Feat

#33 Fix: 알람 기능 개선 진행 중
  src/apis/auth/postSignout.ts
  src/apis/notification/getNotifications.ts
  src/apis/profile/getProfilesCode.ts
  src/app/_components/_Header/AlarmModal.tsx
  src/app/_components/_Header/AlarmModalHeader.tsx
  src/app/_components/_Header/HeaderRight.tsx
  src/app/_components/_Header/MessageAlarm.tsx
  src/app/_components/_Header/UserDropDown.tsx
  src/app/_components/_Header/UserProfileDropdown.tsx
  src/app/wikilist/_components/Profile.tsx
  src/context/AlarmContext.tsx
  src/context/AuthContext.tsx
  src/hooks/useImageLoad.ts
  src/hooks/useResponsive.ts
  src/hooks/useToggle.ts
  src/types/alarm.ts
Labels: 🐛 Fix

#37 🐛 Fix/details: 게시글 상세, 작성 연동
  package.json
  src/app/(boards)/addboard/AddBoardComponent.tsx
  src/app/(boards)/boards/[id]/components/CommentList.tsx
  src/app/(boards)/boards/[id]/components/Content.tsx
  src/app/(boards)/boards/[id]/components/DetailSection.tsx
  src/app/(boards)/boards/[id]/page.tsx
  src/app/(boards)/boards/components/bestArticles/BestHeader.tsx
  src/app/(boards)/boards/components/bestArticles/BestPostCard.tsx
  src/app/(boards)/boards/page.tsx
  src/styles/addboard.css
  src/styles/markdown.module.css
  yarn.lock
Labels: 🐛 Fix

#35 ✨ Feat: 위키 페이지 작업
  package.json
  src/apis/profile/getProfilesCode.ts
  src/apis/profile/patchProfilesCode.ts
  src/apis/profile/postProfiles.ts
  src/apis/profile/postProfilesCodePing.ts
  src/app/(wiki)/wiki/[code]/_constants/editorBasicText.ts
  src/app/(wiki)/wiki/[code]/_constants/formDataInitialValue.ts
  src/app/(wiki)/wiki/[code]/_constants/toast.ts
  src/app/(wiki)/wiki/[code]/_constants/url.ts
  src/app/(wiki)/wiki/[code]/_constants/windowSize.ts
  src/app/(wiki)/wiki/[code]/_hook/useBoolean.tsx
  src/app/(wiki)/wiki/[code]/_hook/useIsMobile.tsx
  src/app/(wiki)/wiki/[code]/_store/useAuthStore.ts
  src/app/(wiki)/wiki/[code]/_store/useStore.ts
  src/app/(wiki)/wiki/[code]/_style/ToastStyle.tsx
  src/app/(wiki)/wiki/[code]/components/Common/CommonButton.tsx
  src/app/(wiki)/wiki/[code]/components/Common/CopyLinkButton.tsx
  src/app/(wiki)/wiki/[code]/components/Common/Input.tsx
  src/app/(wiki)/wiki/[code]/components/Common/Label.tsx
  src/app/(wiki)/wiki/[code]/components/Common/Modal.tsx
  src/app/(wiki)/wiki/[code]/components/Common/ToastSelect.tsx
  src/app/(wiki)/wiki/[code]/components/Common/lottie/check.json
  src/app/(wiki)/wiki/[code]/components/Common/lottie/error.json
  src/app/(wiki)/wiki/[code]/components/Profile/BasicWikiSection.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/Editor.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/ProfileInfos.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/QuizModalTemplete.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/UserProfile.tsx
  src/app/(wiki)/wiki/[code]/page.tsx
  src/app/(wiki)/wikilist/_components/Input.tsx
  src/app/(wiki)/wikilist/_components/PageItem.tsx
  src/app/(wiki)/wikilist/_components/Pagination.tsx
  src/app/(wiki)/wikilist/_components/Profile.tsx
  src/app/(wiki)/wikilist/_components/ProfileList.tsx
  src/app/(wiki)/wikilist/page.tsx
  src/app/wiki/[code]/page.tsx
  src/assets/icons/arrowdown.svg
  src/assets/icons/info.svg
  src/assets/icons/lock.svg
  src/types/apiType.ts
  src/types/toast.ts
  src/utils/cookieUtill.ts
  src/utils/throttle.ts
  src/utils/urlVaildation.ts
  tailwind.config.js
  yarn.lock
Labels: ✨ Feat

#39 🐛fix(비회원 기능): 비회원 좋아요, 댓글 로그인 페이지로 리다이렉트
  src/app/(boards)/boards/[id]/components/CommentForm.tsx
  src/app/(boards)/boards/[id]/components/DetailSection.tsx
  src/app/(boards)/boards/[id]/page.tsx
Labels: 🐛 Fix

#41 🐛fix(signup): 회원가입 오류 수정
  src/apis/auth/postSignUp.ts
  src/app/(auth)/signup/_components/SignUpForm.tsx
Labels: 🐛 Fix

#43 🔨Refactor/style: 자유게시판 css 및 오류 수정
  package.json
  src/app/(boards)/boards/[id]/components/CommentForm.tsx
  src/app/(boards)/boards/[id]/components/CommentList.tsx
  src/app/(boards)/boards/[id]/components/DetailSection.tsx
  src/app/(boards)/boards/[id]/page.tsx
  src/app/(boards)/boards/components/Pagination.tsx
  src/app/(boards)/boards/components/allArticles/AllArticleSection.tsx
  src/app/(boards)/boards/components/allArticles/PostList.tsx
  src/app/_components/Header.tsx
  yarn.lock
Labels: 🐛 Fix

#44 🚨 Fix : 위키 페이지 스타일 수정 및 리뷰 내용 반영
  package.json
  src/app/(wiki)/wiki/[code]/_constants/url.ts
  src/app/(wiki)/wiki/[code]/_store/useAuthStore.ts
  src/app/(wiki)/wiki/[code]/_store/useStore.ts
  src/app/(wiki)/wiki/[code]/components/Profile/ProfileInfos.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/UserProfile.tsx
  src/app/(wiki)/wiki/[code]/page.tsx
  yarn.lock
Labels: 🐛 Fix

#48 🐛Fix/boards: 멘토링 qa 반영
  public/favicon.ico
  src/app/(auth)/login/_components/Button.tsx
  src/app/(auth)/login/_components/Form.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(boards)/addboard/[id]/page.tsx
  src/app/(boards)/addboard/page.tsx
  src/app/(boards)/boards/[id]/components/CommentList.tsx
  src/app/(boards)/boards/[id]/components/DetailSection.tsx
  src/app/(boards)/boards/[id]/page.tsx
  src/app/(boards)/boards/components/bestArticles/BestPostCard.tsx
  src/app/(boards)/boards/page.tsx
  src/app/(wiki)/wiki/[code]/page.tsx
  src/app/(wiki)/wikilist/page.tsx
  src/app/_components/_Header/HeaderLeft.tsx
  src/app/_components/_Header/HeaderRight.tsx
  src/app/_components/_Header/MessageAlarm.tsx
  src/app/_components/_Header/NotUserDropDown.tsx
  src/app/_components/_Header/UserDropDown.tsx
  src/app/_components/_Header/UserProfileDropdown.tsx
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/assets/icons/logo.svg
Labels: 🐛 Fix

#47 🔨Refactor: 알람 무한 스크롤 기능 제작 및 메뉴 일부 구성 변경
  package.json
  src/apis/user/getIP.ts
  src/app/_components/Header.tsx
  src/app/_components/_Header/AlarmModal.tsx
  src/app/_components/_Header/AlarmModalHeader.tsx
  src/app/_components/_Header/HeaderLeft.tsx
  src/app/_components/_Header/HeaderRight.tsx
  src/app/_components/_Header/MessageAlarm.tsx
  src/app/_components/_Header/UserDropDown.tsx
  src/app/_components/_Header/UserLocation.tsx
  src/app/_components/_Header/UserProfileDropdown.tsx
  src/app/not-found-code/page.tsx
  src/context/AlarmContext.tsx
  src/types/alarm.ts
  src/types/user.type.ts
  yarn.lock
Labels: 🔨 Refactor

#49 🔨Refactor/page: 페이지 애니메이션 추가
  package.json
  public/images/landingSwiper1.svg
  public/images/landingSwiper2.svg
  public/images/landingSwiper3.svg
  public/images/landingSwiper4.svg
  src/app/_components/Landing/SwiperSection.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/template.tsx
  yarn.lock
Labels: 🔨 Refactor

#46 🐛 fix: 멘토링 수정 사항 반영
  src/app/(mypage)/changepassword/_components/Button.tsx
  src/app/(mypage)/changepassword/_components/ErrorText.tsx
  src/app/(mypage)/changepassword/_components/Input.tsx
  src/app/(mypage)/changepassword/_components/Label.tsx
  src/app/(mypage)/changepassword/_components/PasswordChangeForm.tsx
  src/app/(mypage)/changepassword/page.tsx
  src/app/(mypage)/makewiki/_components/Button.tsx
  src/app/(mypage)/makewiki/_components/CreateWikiForm.tsx
  src/app/(mypage)/makewiki/_components/ErrorText.tsx
  src/app/(mypage)/makewiki/_components/Input.tsx
  src/app/(mypage)/makewiki/_components/Label.tsx
  src/app/(mypage)/makewiki/page.tsx
  src/app/(wiki)/wiki/[code]/_constants/url.ts
  src/app/(wiki)/wiki/[code]/components/Common/CommonButton.tsx
  src/app/(wiki)/wiki/[code]/components/Common/CopyLinkButton.tsx
  src/app/(wiki)/wiki/[code]/components/Common/MessageModal.tsx
  src/app/(wiki)/wiki/[code]/components/Common/Modal.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/Editor.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/ProfileInfos.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/QuizModalTemplete.tsx
  src/app/(wiki)/wiki/[code]/components/Profile/UserProfile.tsx
  src/app/(wiki)/wiki/[code]/page.tsx
  src/app/mypage/page.tsx
  src/utils/urlVaildation.ts
Labels: 🐛 Fix

#51 Refactor/qa: 메인페이지 gif 추가
  public/images/loading.gif
  src/app/_components/Header.tsx
  src/app/loading.tsx
  src/app/page.tsx
Labels: 🔨 Refactor
